# Generated by Django 5.0.6 on 2024-06-30 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('celebrity', '0020_alter_celebrity_tags'),
        ('movie', '0008_language_movietags_movie_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_slug', models.SlugField(blank=True, editable=False, null=True)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('official_trailer_url', models.URLField(blank=True, null=True)),
                ('plot', models.TextField(blank=True, null=True)),
                ('poster', models.FileField(blank=True, null=True, upload_to='media/web-series/posters/')),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('rotten_tomatoes_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('universal_rating', models.CharField(blank=True, choices=[('G', 'General Audiences – All Ages Admitted'), ('PG', 'Parental Guidance Suggested – Some Material May Not Be Suitable for Children'), ('PG-13', 'Parents Strongly Cautioned – Some Material May Be Inappropriate for Children Under 13'), ('R', 'Restricted – Under 17 Requires Accompanying Parent or Adult Guardian'), ('NC-17', 'Adults Only – No One 17 and Under Admitted'), ('NR', 'Not Rated')], help_text='Universal content rating', max_length=5, null=True)),
                ('verdict', models.CharField(blank=True, choices=[('Hit', 'Hit'), ('Flop', 'Flop'), ('Average', 'Average'), ('Super Hit', 'Super Hit'), ('Blockbuster', 'Blockbuster')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_on', models.ManyToManyField(related_name='web_series', to='movie.availablemedia')),
                ('director', models.ManyToManyField(blank=True, related_name='by_directed_web_series', to='celebrity.celebrity')),
                ('genres', models.ManyToManyField(related_name='web_series_genres', to='movie.genre')),
                ('language', models.ManyToManyField(blank=True, to='movie.language')),
                ('producers', models.ManyToManyField(blank=True, related_name='produced_web_series', to='celebrity.celebrity')),
                ('tags', models.ManyToManyField(related_name='web_series_tags', to='movie.movietags')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_slug', models.SlugField(blank=True, editable=False, null=True)),
                ('plot', models.TextField(blank=True, null=True)),
                ('season_number', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='media/web-series/seasons/posters/')),
                ('promotional_video_url', models.URLField(blank=True, null=True)),
                ('universal_rating', models.CharField(blank=True, choices=[('G', 'General Audiences – All Ages Admitted'), ('PG', 'Parental Guidance Suggested – Some Material May Not Be Suitable for Children'), ('PG-13', 'Parents Strongly Cautioned – Some Material May Be Inappropriate for Children Under 13'), ('R', 'Restricted – Under 17 Requires Accompanying Parent or Adult Guardian'), ('NC-17', 'Adults Only – No One 17 and Under Admitted'), ('NR', 'Not Rated')], help_text='Universal content rating', max_length=5, null=True)),
                ('verdict', models.CharField(blank=True, choices=[('Hit', 'Hit'), ('Flop', 'Flop'), ('Average', 'Average'), ('Super Hit', 'Super Hit'), ('Blockbuster', 'Blockbuster')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_languages', models.ManyToManyField(blank=True, help_text='Available Audio languages', related_name='season_audio_language', to='movie.language')),
                ('available_on', models.ManyToManyField(related_name='web_series_media', to='movie.availablemedia')),
                ('subtitle_languages', models.ManyToManyField(blank=True, help_text='Available subtitle languages', related_name='season_subtitle_language', to='movie.language')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='webseries.webseries')),
            ],
            options={
                'ordering': ['season_number'],
            },
        ),
        migrations.CreateModel(
            name='WebSeriesCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celebrity.celebrity')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='celebrity.role')),
                ('web_series_worked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_series_worked', to='webseries.season')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='acted_web_series', through='webseries.WebSeriesCast', to='celebrity.celebrity'),
        ),
        migrations.CreateModel(
            name='WebSeriesRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('max_rating', models.IntegerField()),
                ('url', models.URLField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_series_ratings', to='movie.ratingagency')),
                ('webSeries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_series_ratings', to='webseries.season')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=555)),
                ('title_slug', models.SlugField(blank=True, editable=False, null=True)),
                ('plot', models.TextField(blank=True, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='media/web-series/seasons/episodes/posters/')),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('release_date', models.DateField()),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('has_subtitles', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_languages', models.ManyToManyField(blank=True, help_text='Available Audio languages', related_name='epdisode_audio_language', to='movie.language')),
                ('subtitle_languages', models.ManyToManyField(blank=True, help_text='Available subtitle languages', related_name='epidosde_subtitle_language', to='movie.language')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='webseries.season')),
            ],
            options={
                'ordering': ['episode_number'],
                'unique_together': {('season', 'episode_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('series', 'season_number')},
        ),
    ]
