# Generated by Django 5.0.6 on 2024-06-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='celebrities/'),
        ),
        migrations.AddField(
            model_name='celebrity',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='biography',
            name='zodiac_sign',
            field=models.CharField(blank=True, choices=[('Aries', 'Aries'), ('Taurus', 'Taurus'), ('Gemini', 'Gemini'), ('Cancer', 'Cancer'), ('Leo', 'Leo'), ('Virgo', 'Virgo'), ('Libra', 'Libra'), ('Scorpio', 'Scorpio'), ('Sagittarius', 'Sagittarius'), ('Capricorn', 'Capricorn'), ('Aquarius', 'Aquarius'), ('Pisces', 'Pisces')], max_length=50, null=True),
        ),
    ]
