# Generated by Django 5.0.6 on 2024-06-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrity', '0002_celebrity_image_celebrity_is_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celebrity',
            name='industry',
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='roles',
            field=models.ManyToManyField(related_name='celebrities_role', to='celebrity.role'),
        ),
        migrations.AddField(
            model_name='celebrity',
            name='industry',
            field=models.ManyToManyField(related_name='celebrities_industry', to='celebrity.filmindustry'),
        ),
    ]
