# Generated by Django 5.0.6 on 2024-06-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrity', '0004_delete_award_delete_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/celebrities/'),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/celebrities/'),
        ),
    ]
