# Generated by Django 5.0.6 on 2024-06-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrity', '0006_celebrity_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='CelebrityTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_slug', models.SlugField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='celebrity',
            name='tags',
            field=models.ManyToManyField(related_name='celebrities_tags', to='celebrity.celebritytags'),
        ),
    ]
