# Generated by Django 5.0.6 on 2024-06-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrity', '0007_celebritytags_celebrity_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='favorite_actress',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='biography',
            name='favorite_beverage',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='biography',
            name='favorite_bollywood_actor',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='biography',
            name='favorite_cars',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='biography',
            name='favorite_color',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='biography',
            name='favorite_cricketers',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='biography',
            name='favorite_dessert',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='biography',
            name='favorite_fashion_brands',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='biography',
            name='favorite_film',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='biography',
            name='favorite_film_director',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='biography',
            name='favorite_hollywood_actor',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='biography',
            name='favorite_outfit',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='biography',
            name='favorite_perfume',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='biography',
            name='favorite_restaurant',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='biography',
            name='favorite_singer',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='biography',
            name='favorite_song',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='biography',
            name='favorite_sport',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='biography',
            name='followers_unit',
            field=models.CharField(choices=[('million', 'Million')], default='million', max_length=8),
        ),
        migrations.AddField(
            model_name='biography',
            name='worth_value_unit',
            field=models.CharField(choices=[('crores', 'Crores')], default='crores', max_length=8),
        ),
        migrations.AlterField(
            model_name='biography',
            name='college',
            field=models.CharField(blank=True, max_length=1255, null=True),
        ),
        migrations.AlterField(
            model_name='biography',
            name='favorite_food',
            field=models.CharField(blank=True, max_length=1255, null=True),
        ),
        migrations.AlterField(
            model_name='biography',
            name='hometown',
            field=models.CharField(blank=True, max_length=1255, null=True),
        ),
        migrations.AlterField(
            model_name='biography',
            name='school',
            field=models.CharField(blank=True, max_length=1255, null=True),
        ),
    ]
