# Generated by Django 5.0.6 on 2024-06-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrity', '0008_biography_favorite_actress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in Kg', max_digits=15, null=True),
        ),
    ]
