# Generated by Django 5.0.6 on 2024-06-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrity', '0009_biography_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='instagram_followers',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Followers in Million', max_digits=15, null=True),
        ),
    ]
