# Generated by Django 5.0.6 on 2024-06-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrity', '0010_alter_biography_instagram_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='biceps',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='biography',
            name='caste',
            field=models.CharField(blank=True, max_length=1255, null=True),
        ),
        migrations.AddField(
            model_name='biography',
            name='chest',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='biography',
            name='hobbies',
            field=models.CharField(blank=True, max_length=1255, null=True),
        ),
        migrations.AddField(
            model_name='biography',
            name='religion',
            field=models.CharField(blank=True, max_length=1255, null=True),
        ),
        migrations.AddField(
            model_name='biography',
            name='salary_currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('INR', 'INR'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='biography',
            name='salary_note',
            field=models.CharField(blank=True, max_length=1255, null=True),
        ),
        migrations.AddField(
            model_name='biography',
            name='salary_per_film',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='biography',
            name='salary_value_unit',
            field=models.CharField(choices=[('crores', 'Crores')], default='crores', max_length=8),
        ),
        migrations.AddField(
            model_name='biography',
            name='waist',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='biography',
            name='birthplace',
            field=models.CharField(blank=True, max_length=1255, null=True),
        ),
    ]
