# Generated by Django 5.0.6 on 2024-06-30 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrity', '0011_biography_biceps_biography_caste_biography_chest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiographyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('biography_type', models.CharField(choices=[('bio/wiki', 'Bio/Wiki'), ('physicalStats', 'Physical Stats'), ('favourites', 'Favourites')], default='bio/wiki', max_length=100)),
                ('platform_type', models.CharField(choices=[('instagram', 'Instagram'), ('twitter', 'Twitter'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('pinterest', 'Pinterest')], default='instagram', max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='media/celebrities/biography/')),
                ('embedded_code', models.TextField(blank=True, null=True)),
                ('biography', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biography_media', to='celebrity.biography')),
            ],
            options={
                'verbose_name': 'Biography Media',
                'verbose_name_plural': "Biography Media's",
            },
        ),
        migrations.CreateModel(
            name='CelebrityFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('platform_type', models.CharField(choices=[('instagram', 'Instagram'), ('twitter', 'Twitter'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('pinterest', 'Pinterest')], default='instagram', max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='media/celebrities/facts/')),
                ('embedded_code', models.TextField(blank=True, null=True)),
                ('celebrity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='celebrity_facts', to='celebrity.celebrity')),
            ],
            options={
                'verbose_name': 'Celebrity Fact',
                'verbose_name_plural': 'Celebrity Facts',
            },
        ),
    ]
