# Generated by Django 5.0.6 on 2024-06-30 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celebrity', '0012_biographymedia_celebrityfacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biographymedia',
            name='text',
        ),
    ]
