# Generated by Django 5.0.6 on 2024-06-30 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrity', '0013_remove_biographymedia_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CelebrityFAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Celebrity FAQ Category',
                'verbose_name_plural': 'Celebrity FAQ Categories',
            },
        ),
        migrations.CreateModel(
            name='CelebrityFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('priority', models.IntegerField(default=0)),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='celebrity.celebrity')),
                ('category', models.ManyToManyField(related_name='faqs', to='celebrity.celebrityfaqcategory')),
            ],
            options={
                'verbose_name': 'Celebrity FAQ',
                'verbose_name_plural': 'Celebrity FAQs',
                'ordering': ['priority', 'date_created'],
            },
        ),
    ]
