# Generated by Django 5.0.6 on 2024-06-30 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrity', '0014_celebrityfaqcategory_celebrityfaq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrityfacts',
            name='celebrity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celebrity_facts', to='celebrity.celebrity'),
        ),
    ]
