# Generated by Django 5.0.6 on 2024-06-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celebrity', '0016_spotlightcelebrities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpotlightCelebrities',
        ),
    ]
