# Generated by Django 5.0.6 on 2024-06-30 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrity', '0017_delete_spotlightcelebrities'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='body_figure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CelebrityRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('step_father', 'Step Father'), ('step_mother', 'Step Mother'), ('girlfriend', 'Girlfriend'), ('boyfriend', 'Boyfriend'), ('sister', 'Sister'), ('brother', 'Brother'), ('affair', 'Affair')], max_length=50)),
                ('relates_relationship_type', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('step_father', 'Step Father'), ('step_mother', 'Step Mother'), ('girlfriend', 'Girlfriend'), ('boyfriend', 'Boyfriend'), ('sister', 'Sister'), ('brother', 'Brother'), ('affair', 'Affair')], max_length=50)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='media/celebrities/celebrity_relations/')),
                ('embedded_code', models.TextField(blank=True, null=True)),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='celebrity.celebrity')),
                ('related_celebrity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationships_to', to='celebrity.celebrity')),
            ],
            options={
                'verbose_name': 'Celebrity Relationship',
                'verbose_name_plural': 'Celebrity Relationships',
            },
        ),
    ]
