# Generated by Django 5.0.6 on 2024-06-30 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrity', '0018_biography_body_figure_celebrityrelationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='CelebrityControversies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('platform_type', models.CharField(choices=[('instagram', 'Instagram'), ('twitter', 'Twitter'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('pinterest', 'Pinterest')], default='instagram', max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='media/celebrities/controversies/')),
                ('embedded_code', models.TextField(blank=True, null=True)),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celebrity_controversies', to='celebrity.celebrity')),
            ],
            options={
                'verbose_name': 'Celebrity Controversies',
                'verbose_name_plural': 'Celebrity Controversies',
            },
        ),
    ]
