# Generated by Django 5.0.6 on 2024-06-14 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='vehicle.vehiclemaker'),
            preserve_default=False,
        ),
    ]
