# Generated by Django 5.0.6 on 2024-06-09 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('celebrity', '0003_remove_celebrity_industry_alter_celebrity_roles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_slug', models.SlugField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RatingAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celebrity.celebrity')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='celebrity.role')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('plot', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('budget_currency', models.CharField(blank=True, choices=[('USD', 'USD'), ('INR', 'INR'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('Other', 'Other')], max_length=10, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('poster', models.FileField(blank=True, null=True, upload_to='movies/posters/')),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('rotten_tomatoes_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('verdict', models.CharField(blank=True, choices=[('Hit', 'Hit'), ('Flop', 'Flop'), ('Average', 'Average'), ('Super Hit', 'Super Hit'), ('Blockbuster', 'Blockbuster')], max_length=20, null=True)),
                ('cast', models.ManyToManyField(blank=True, related_name='acted_movies', through='movie.Cast', to='celebrity.celebrity')),
                ('director', models.ManyToManyField(blank=True, related_name='by_directed_movies', to='celebrity.celebrity')),
                ('genres', models.ManyToManyField(related_name='movies', to='movie.genre')),
                ('producers', models.ManyToManyField(blank=True, related_name='produced_movies', to='celebrity.celebrity')),
            ],
        ),
        migrations.AddField(
            model_name='cast',
            name='movie_worked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_worked', to='movie.movie'),
        ),
        migrations.CreateModel(
            name='BoxOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('country', models.CharField(choices=[('India', 'India'), ('USA', 'USA'), ('UK', 'UK'), ('China', 'China'), ('Worldwide', 'Worldwide')], max_length=20)),
                ('collection_currency', models.CharField(blank=True, choices=[('USD', 'USD'), ('INR', 'INR'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('Other', 'Other')], max_length=10, null=True)),
                ('collection', models.DecimalField(decimal_places=2, max_digits=15)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_office_figures', to='movie.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('max_rating', models.IntegerField()),
                ('url', models.URLField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movie.movie')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movie.ratingagency')),
            ],
        ),
    ]
