# Generated by Django 5.0.6 on 2024-06-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='title_slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
