# Generated by Django 5.0.6 on 2024-06-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_title_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='available_on',
            field=models.CharField(blank=True, choices=[('Theater', 'Theater'), ('Prime', 'Prime'), ('Netflix', 'Netflix'), ('Jio Cinema', 'Jio Cinema'), ('Apple TV', 'Apple TV'), ('Zee5', 'Zee5'), ('Disney Hotstar', 'Disney Hotstar'), ('MX Player', 'MX Player'), ('Voot', 'Voot')], max_length=20, null=True),
        ),
    ]
