# Generated by Django 5.0.6 on 2024-06-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_availablemedia_remove_movie_available_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.FileField(blank=True, null=True, upload_to='media/movies/posters/'),
        ),
    ]
