# Generated by Django 5.0.6 on 2024-06-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_movie_available_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxoffice',
            name='collection_currency',
        ),
        migrations.AddField(
            model_name='boxoffice',
            name='day',
            field=models.CharField(choices=[('day1', 'Day 1'), ('day2', 'Day 2'), ('day3', 'Day 3'), ('day4', 'Day 4'), ('day5', 'Day 5'), ('day6', 'Day 6'), ('day7', 'Day 7'), ('day8', 'Day 8'), ('day9', 'Day 9'), ('day10', 'Day 10'), ('day11', 'Day 11'), ('day12', 'Day 12'), ('day13', 'Day 13'), ('day14', 'Day 14'), ('day15', 'Day 15')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='boxoffice',
            name='value_unit',
            field=models.CharField(choices=[('crores', 'Crores')], default='crores', max_length=8),
        ),
        migrations.AddField(
            model_name='movie',
            name='budget_unit',
            field=models.CharField(choices=[('crores', 'Crores')], default='crores', max_length=8),
        ),
        migrations.AddField(
            model_name='movie',
            name='collection_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('INR', 'INR'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('Other', 'Other')], default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='boxoffice',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='budget_currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('INR', 'INR'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('Other', 'Other')], default='INR', max_length=10, null=True),
        ),
    ]
