# Generated by Django 5.0.6 on 2024-06-30 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlights', '0001_initial'),
        ('webseries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotlightWebSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(blank=True, help_text='Optional Heading', null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description or highlight text.', null=True)),
                ('active', models.BooleanField(default=True, help_text='Toggle visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('web_series', models.ManyToManyField(related_name='spotlight_movies', to='webseries.webseries')),
            ],
            options={
                'verbose_name': 'Spotlight Web Series',
                'verbose_name_plural': 'Spotlight Web Series',
            },
        ),
    ]
