# Generated by Django 5.0.6 on 2024-06-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productRecommend', '0002_remove_product_url_product_price_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatelink',
            name='platform',
            field=models.CharField(choices=[('Amazon', 'Amazon'), ('eBay', 'eBay'), ('Walmart', 'Walmart'), ('Flipkart', 'Flipkart'), ('Other', 'Other')], max_length=50),
        ),
    ]
