# Generated by Django 5.0.6 on 2024-06-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productRecommend', '0003_alter_affiliatelink_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='productRecommend.category'),
        ),
    ]
