# Generated by Django 5.0.6 on 2024-06-11 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('celebrity', '0004_delete_award_delete_movie'),
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='awards/')),
            ],
        ),
        migrations.CreateModel(
            name='AwardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='awards.award')),
            ],
            options={
                'unique_together': {('award', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AwardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)])),
                ('location', models.CharField(blank=True, max_length=500)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='awards.award')),
            ],
            options={
                'unique_together': {('award', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='awards.awardcategory')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='awards.awardevent')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='movie.movie')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominations', to='celebrity.celebrity')),
            ],
            options={
                'unique_together': {('category', 'event', 'person', 'movie')},
            },
        ),
    ]
