# Generated by Django 5.0.6 on 2024-06-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardevent',
            name='title',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='award',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/awards/'),
        ),
    ]
