# Generated by Django 5.0.6 on 2024-06-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_awardevent_title_alter_award_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='name_slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='awardcategory',
            name='name_slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='awardevent',
            name='title_slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
