# Generated by Django 5.0.6 on 2024-06-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_award_awarded_for_award_country_award_first_awarded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardevent',
            name='poster',
            field=models.FileField(blank=True, null=True, upload_to='media/awards/'),
        ),
    ]
